import Head from 'next/head'
import { Hero } from '@/widgets/HeroSection'
import { InfoSection } from '@/widgets/InfoSection'
import DeepResearch from '@/widgets/DeepResearch/ui/DeepResearch'
import { QR } from '@/widgets/QRSection'
import { Technologies } from '@/widgets/Technologies'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cirle Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/CircleUp.png" />
      </Head>
    <Hero/>
    {/* <InfoSection/> */}
    {/* <DeepResearch/>
    <Technologies/>
    <QR/> */}
    </>
  )
}